### PR TITLE
Added Zephir Parser support

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by mlocati** [comment]
:+1: thanks!

**Comment by mlocati** [comment]
I just released version 1.22.2.295 containing this fix

**Comment by sergeyklay** [comment]
You're welcome :)

**Comment by mlocati** [comment]
PS: I just released version 1.22.3.298 with [this change](https://github.com/mlocati/powershell-phpmanager/commit/f3e0ff79a40a1503353fb79741f01d37d20214fe): from now on, the `Get-PhpExtensionHandle` command builds the extension handle by replacing spaces with `_`. That way, extension with names like `Zephir Parser` become automatically `zephir_parser` without the need of special case handling.

**Comment by sergeyklay** [comment]
Thank you!

**Pull request merged**
